### ISSUE TITLE
请问会收集马前卒在"天涯论坛"的发言和相关文章吗?

### ISSUE THREAD

**Issue by zedrun00** [ktKongTong/btnews#55]
![image](https://github.com/ktKongTong/btnews/assets/104408400/afb3a699-331a-4dbb-b9ed-c47f103c4107)

**Comment by ktKongTong** [comment]
不会。

- 第一，这个仓库只是用空闲时间建立的，仅一个人维护。其主要目标旨在收集睡前消息工作室的睡前消息这一栏目的文稿内容，马前卒个人早期的文章/发言，不在目标范围之内。
- 第二，退一步说，目前该仓库内容均是自动化收集的，在天涯论坛已关闭的情况下，着手收集其天涯发言/文章的难度也是十分巨大的，自动收集的可能性不大，手动搜集也很难办到。

不过也别灰心，可以在另外一个类似站点 [bedtime.news](https://archive.bedtime.news/) 的评论区中进行询问。若你已有部分内容的文稿，也可以提交相关内容的PR到对应仓库 https://github.com/bedtimenews/bedtimenews-archive-contents
